name: NPM publish CD workflow

on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  publish:
    if: github.event.release.target_commitish == 'main' || github.event.release.target_commitish == 'next'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # "ref" specifies the branch to check out.
          # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          # Specifies the registry, this field is required!
          registry-url: https://registry.npmjs.org/
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: git config --global user.name "GitHub Release Bot"
      - run: git config --global user.email "github-release-bot@codeful.dev"

      # upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }} -m "Bump version %s"
      - name: Publish next release
        if: github.event.release.target_commitish == 'next'
        run: npm publish --ignore-scripts --tag=next
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish beta release
        if: github.event.release.target_commitish != 'main' && github.event.release.target_commitish != 'next'
        run: npm publish --ignore-scripts --tag=beta
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish stable release
        if: github.event.release.target_commitish == 'main'
        run: npm publish --ignore-scripts
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/v${{ github.event.release.tag_name }}
          delete-branch: true
          title: Release v${{ github.event.release.tag_name }}
          reviewers: dwightjack
          committer: GitHub Release Bot <github-release-bot@codeful.dev>
